#!/usr/bin/env bash

protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]
then
    echo "Cannot push to master branch"
    exit 1 # push will not execute
else
    exit 0 # push will execute
fi