name: build-release

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
            # Mostly to avoid GitHub rate limiting
    extra_nix_config: |
        access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Build release
        run: nix develop --command ./buildForWindows.sh
    # steps:
    # - uses: actions/checkout@v4

    # - name: Set up Go
    #   uses: actions/setup-go@v4
    #   with:
    #     go-version: '1.20'

    # - name: Build
    #   run: go build -v ./...

    # - name: Test
    #   run: go test -v ./...
